---
# this playbook is based on that instructions: https://medium.com/@a_tsai5/creating-an-ec2-instance-using-ansible-764cf70015f6
# hosts is localhost since the python script is runnig on my local machine
- hosts: localhost
  connection: local
  gather_facts: False

  vars:
    key_name: my_aws             # Key used for SSH
    image: ami-06cd706b6bacee637 # look in ec2 > ami (filter owner alias: amazon) or amis of manually launched instances
    id: "example testing"
    instance_type: t2.nano       # Choose instance type, check AWS for pricing
    sec_group: "test-security-group"

  tasks:
    - name: Provisioning EC2 instances
      block:

      - name: Create security group
        amazon.aws.ec2_security_group:
          name: "{{ sec_group }}"
          description: "Sec group for app"
          region: "{{ region }}"
          aws_access_key: "{{ec2_access_key}}"  # From vault as defined
          aws_secret_key: "{{ec2_secret_key}}"  # From vault as defined
          state: present
          rules:                                # allows ssh on port 22
            - proto: tcp
              ports:
                - 22
                - 443
                - 80  
              cidr_ip: 0.0.0.0/0
              rule_desc: allow all on ssh port

      - name: Amazon EC2 | Create Key Pair      # Create key pair for ssh
        amazon.aws.ec2_key:
          name: "{{ key_name }}"
          region: "{{ region }}"
          aws_access_key: "{{ec2_access_key}}"  # From vault as defined
          aws_secret_key: "{{ec2_secret_key}}"  # From vault as defined
          key_material: "{{ item }}"
          state: present
        with_file: "{{path_to_my_aws_pub_key}}"

      - name: Start an instance with a public IP address
        amazon.aws.ec2_instance:
          name: "public-compute-instance"
          key_name: "{{ key_name }}"
          # vpc_subnet_id: "{{ vpc_id }}"
          instance_type: "{{ instance_type }}"
          security_group: "{{ sec_group }}"
          aws_access_key: "{{ ec2_access_key }}"
          aws_secret_key: "{{ ec2_secret_key }}"
          state: present
          region: "{{ region }}"
          network:
            assign_public_ip: true
          image_id: "{{ image }}"
          tags:
            Environment: Testing

      # Always require the 'create_ec2' tag to provision EC2 instance
      tags: ['never', 'create_ec2'] 

    - name: Facts
      block: # this block prints out instance data

      - name: Get instances facts
        ec2_instance_info:
          aws_access_key: "{{ ec2_access_key }}"
          aws_secret_key: "{{ ec2_secret_key }}"
          region: "{{ region }}"
        register: result

      - name: Instances ID
        debug:
          msg: "ID: {{ item.instance_id }} - State: {{ item.state.name }} - Public DNS: {{ item.public_dns_name }}"
        loop: "{{ result.instances }}"
      tags: always
